
# retriever.py
import chromadb
#from mistralai import Mistral
from google import genai
from typing import List
import dotenv
import os

dotenv.load_dotenv()

# create a single long-lived client (or use 'with Mistral(...) as client:' if you prefer context manager)

#print(os.getenv("MISTRAL_API_KEY"))
genai_client = genai.Client()  # will use GEMINI_API_KEY env var if None

class VectorStore:
    def __init__(self, collection_name="docs"):
        # Chroma 0.5+ PersistentClient
        self.chroma = chromadb.PersistentClient(path="./chroma_db")
        self.collection = self.chroma.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"}  # optional
        )

    def add_texts(self, texts: List[str], ids: List[str] = None):
        """
        Add a list of texts to Chroma using Mistral embeddings.
        texts: list of strings
        ids: optional list of ids matching texts; otherwise autogenerated
        """
        if not texts:
            return

        # Get embeddings in batch — NOTE: parameter name is `inputs`
        resp = genai_client.models.embed_content(
            model="gemini-embedding-001",
            contents=texts
        )

        embedding_list = [embedding.values for embedding in resp.embeddings]

        # Build ids if not provided
        if ids is None:
            #start_idx = len(self.collection.get(include=["metadatas", "ids", "documents"])["ids"])
            #ids = [f"doc_{start_idx + i}" for i in range(len(texts))]
            ids = [f"doc_{i}" for i in range(len(texts))]

        # Add to Chroma collection
        self.collection.add(
            documents=texts,
            embeddings=embedding_list,
            ids=ids
        )

    def search(self, query: str, k: int = 100) -> List[str]:
        # Create embedding for query (single input -> still pass as list)
        q_resp = genai_client.models.embed_content(
            model="gemini-embedding-001",
            contents=[query]
        )
        q_emb = q_resp.embeddings[0].values

        result = self.collection.query(
            query_embeddings=[q_emb],
            n_results=k,
            #include=["documents", "distances", "ids"]
            include=["documents", 'distances']
        )

        # result["documents"] is a list-of-lists: one list per query
        return result["documents"][0]
